### ISSUE TITLE
Preserve 'tel:' when exporting?

### ISSUE THREAD

**Issue by rolandog** [mistrey/org-dial#2]
Could it be possible to preserve the  `tel:` prefix when exporting?  I get a PDF which thinks that there is, for example, a `+123456789.pdf` target for a phone link.

**Comment by mistrey** [comment]
We will have to add an EXPORT function in line 35.
https://doc.endlessparentheses.com/Fun/org-add-link-type
Here is an example: https://github.com/yyr/org-mode/blob/master/lisp/org-bbdb.el

**Comment by rolandog** [comment]
Indeed!  I also found the [Adding Hyperlink types](https://orgmode.org/manual/Adding-Hyperlink-Types.html) section in the Org-mode manual, and it also has a nice example as well.

Do you want me to submit a pull-request?

**Comment by mistrey** [comment]
I just noticed that org-add-link-type is obsolete. Please give me some minutes to make a proposal. I would appreciate if you could test the new version.

**Comment by rolandog** [comment]
Of course!  There's no hurry.  I'd be happy to test the new version when it's available.  Thank you very much in advance for your help.

**Comment by mistrey** [comment]
I just pushed my changes -- all untested. John Kitchen is my hero https://kitchingroup.cheme.cmu.edu/blog/2016/11/04/New-link-features-in-org-9/.
Thank you for testing!

**Comment by mistrey** [comment]
Fixed and tested with HTML, LaTeX and ODT export.

**Comment by rolandog** [comment]
You're welcome! Thanks for the quick response!

I tested the three possible outputs (though it would be nice to also include `'ascii` and maybe even `'texinfo` too), and the catch-all as well.

Here's the test document:

``` console
user@computer:~$ cat ~/org/phone.org
[[tel:+1234567890][+1 234-567-890]]

[[tel:+1234567890][phone]]
```

And here is the relevant output for all three:

- `'html`: `<a href="+1234567890">+1 234-567-890</a>` *(target would point to `~/org/+1234567890`)*
- `'latex`: `+1 234-567-890` *(no hyperlink)*
- `'odt`: `<text:span text:style-name="Emphasis">+1 234-567-890</text:span>` *(italicized, but no hyperlink)*
- `'ascii`: *(only the description, so I got `phone` for the second case.)*

As you can see, all cases had some sort of bug.

How do you feel about leaving the choice of italicizing to the user, and only setting a hyperlink?

If so, then this modified version of the export code may be useful:

``` lisp
(defun org-dial-export (path desc format)
  "Create the export version of a tel link specified by PATH or DESC."
  (when (string= desc (format "tel:%s" path))
    (setq desc path))
  (cond
   ((eq format 'ascii) (format "%s (%s)" desc (org-dial-trim-phone-number path)))
   ((eq format 'html) (format "<a href=\"tel:%s\">%s</a>" (org-dial-trim-phone-number path) desc))
   ((eq format 'latex) (format "\\href{tel:%s}{%s}" (org-dial-trim-phone-number path) desc))
   ((eq format 'odt)
    (format "<text:a xlink:type=\"simple\" xlink:href=\"tel:%s\">%s</text:a>" (org-dial-trim-phone-number path) desc))
   ((eq format 'texinfo) (format "@url{tel:%s, %s}" (org-dial-trim-phone-number path) desc))
   (t desc)))
```

I tested the code changes, and here is the output for each tested case:

- `'html`: `<a href="tel:+1234567890">+1 234-567-890</a>`
- `'latex`: `\href{tel:+1234567890}{+1 234-567-890}`
- `'odt`: `<text:a xlink:type="simple" xlink:href="tel:+1234567890">+1 234-567-890</text:a>`
- `'ascii`: `phone (+1234567890)`
- `'texinfo`: `@url{tel:+1234567890, phone}`

Note: [Texinfo itself uses different representations when the output is HTML, TeX (and PDF), or Info](https://www.gnu.org/software/texinfo/manual/texinfo/html_node/_0040url-Examples.html).

Update: change example's target from: +0 123-456-789 to: +1 234-567-890 as Skype ignores that target.

**Comment by rolandog** [comment]
After some consideration, perhaps the `'ascii` format could be used in place of the 'else'  condition at the end?  What do you think?

**Comment by mistrey** [comment]
Your pull request will be very welcome. Regarding your last question, I don't have a strong opinion.

**Comment by mistrey** [comment]
Closed with https://github.com/mistrey/org-dial/commit/45acb1a3e3e5421c3dc7a201b46b5986776b5f07

**Comment by rolandog** [comment]
Thank you for the fix!  It works really well.
